server:
  port: ${PORT:8081}

spring:
  application:
    name: backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/resumerank}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true

jwt:
  secret: ${JWT_SECRET:dGhpcy1pcy1hLXN1cGVyLXNlY3JldC1rZXktdGhhdC1pcy1hdC1sZWFzdC0yNTYtYml0cy1sb25nLWZvci1obWFj}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:ljaq2uvl}
  api-key: ${CLOUDINARY_API_KEY:437827782945956}
  api-secret: ${CLOUDINARY_API_SECRET:jDGM09e7HqnqWoWnyUoxsJvUHXk}

resend:
  api-key: ${RESEND_API_KEY:}
  from-address: ${RESEND_FROM_ADDRESS:onboarding@resend.dev}

app:
  frontend-url: ${FRONTEND_URL:http://localhost:3000}
